### ISSUE TITLE
Stranica za dodavanje računa

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#10]
### Pristup stranici
Ovoj stranici se pristupa jedino iz liste računa

### Izgled stranice
Ova stranica sadrži
- Polje za unos JMBG korisnika
- Dugme za pretragu korisnika
- Dugme za kreiranje korisnika

![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/33495263/d32085d5-8238-431e-9ecf-49cd4790f125)
![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/33495263/ebaf0072-ecf6-437d-b649-bdb817ec5556)

- Dugme ,,Kreiraj"

### Funkcionalnosti stranice
Dugme za pretragu korisnika šalje zahtev za pretragu korisnika pomoću JMBG-a na bekend
Dugme za kreiranje korisnika otvara stranicu za kreiranje korisnika za račun
Dugme za kreiranje računa vraća zaposlenog na listu računa

### Validacija stranice
Broj računa je isključivo niz cifara kojih ima 18 
Potrebno je da je validan JMBG unesen (13 cifara) kako bi bilo moguće kliknuti na dugme za pretragu
Potrebno je da su sva polja popunjena da bi moglo da se pritisne dugme za kreiranje računa
Potrebno je sačuvati sadržaj tranice ukoliko se klikne dugme za kreiranje korisnika kako se ne bi izgubio unet sadržaj

**Comment by jovanAtRellify** [comment]
![Screenshot 2024-03-11 at 20 30 28](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/119661870/4d78bbcb-cf92-42a7-b0dc-d7ea15af8613)
Prosirenje za stranicu za kreiranje firminih racuna
