### ISSUE TITLE
Kreiranje stranice moje hartije

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#145]
Potrebno je premestiti "Moje akcije" iz stranice liste akcija kao jedan od tabova tabele

Potrebno je kreirati tabelu sa tabovima za određene hartije od vrednosti koje pripadaju ulogovanom korisniku ili njegovoj firmi
Potrebno je da obični korisnici vide svoje akcije, opcije i porudžbine, dok zaposlenima se na osnovu permisija za akcije, opcije, porudžbine i terminske ugovore određuje šta od toga vide u tabeli.

**Comment by stodorovic9521rn** [comment]
> Potrebno je premestiti "Moje akcije" iz stranice liste akcija kao jedan od tabova tabele
> 
> Potrebno je kreirati tabelu sa tabovima za određene hartije od vrednosti koje pripadaju ulogovanom korisniku ili njegovoj firmi Potrebno je da obični korisnici vide svoje akcije, opcije i porudžbine, dok zaposlenima se na osnovu permisija za akcije, opcije, porudžbine i terminske ugovore određuje šta od toga vide u tabeli.
