### ISSUE TITLE
Kreirati stranicu za porudžbine

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#146]
Potrebno je kreirati stranicu za listanje kupovanje porudžbina koju korisnici vide uvek a zaposleni samo ako imaju `order_access` permisiju

Potrebno je kreirati stranicu za odbijanje/odobravanje i istoriju odobrenih/odbijenih porudžbina koju vide zaposleni sa `list_orders` permisijom, takođe dugmad za odbijanje i odobravanje moraju biti iza odgovarajućih permisija

Porudžbina ima:
- Tip
- Ticker
- Kolicinu
- Cenu po komadu
- Ukupnu cenu
- Ko je napravio porudžbinu
- Da li je odbijena, odobrena ili na čekanju
- Ko je odobrio porudžbinu

Tražiti objekat i rute od backenda i postaviti ih u StockRoutes enum

Koristiti ovo gore kao osnovu za tabelu iz #145

**Comment by BogBogdan** [comment]
Izmena speficikacije:  Donja stranica treba da ima dugme za pravljenje ordera.
