### ISSUE TITLE
Stanica za izveštaj o ostvarenim profitima banke po transakcijama u menjačnici (strana 120)

### ISSUE THREAD

**Issue by matejavasic8321rn** [RAF-SI-2023/Banka-4-Frontend#160]
Potrebno je implementirati prikaz profita po transakcijama na strani banke. Primer se nalazi na strani 121

**Comment by CommandLineFox** [comment]
String sender account (broj racuna)
To account (broj racuna na koji se salje)
Sender amount (broj koliko je poslato)
Sender currency (valuta iz koje)
To currency (valuta u koju)
Exchange rate (rate koliko se dobije)
Profit ce se uzeti i sabirace se na dnu

**Comment by CommandLineFox** [comment]
Pitati Mateju ako nije jasno ili Petra
