### ISSUE TITLE
Prikaz profita na nivou celokupne banke, prikaz bankinih računa i transakcije koje su se izvršile na njima

### ISSUE THREAD

**Issue by matejavasic8321rn** [RAF-SI-2023/Banka-4-Frontend#161]
Potrebno je implementirati prikaz profita na nivou celokupne banke. Ovo se može nalaziti napočetnoj strani ili da se otvara klikom u navbaru. Primer stranice se nalazi na strani 122

Takodje je potrebno odradiit prikaz bankinih računa i klikom na taj račun se može otvoriti tabela transakcija na tom računu. Primeri na stranici 123

**Comment by CommandLineFox** [comment]
Postaviti kao deo sofijine nove stranice https://github.com/RAF-SI-2023/Banka-4-Frontend/issues/160#issuecomment-2151097518

Cekamo backend za rute za ovo
