### ISSUE TITLE
Prikaz profita za individualne agente

### ISSUE THREAD

**Issue by matejavasic8321rn** [RAF-SI-2023/Banka-4-Frontend#162]
Potrebno je napraviti prikaz za profite za individualne agente. Ovo se može nalaziti samo na ekranu supervizora koji će imati listu agenata gde će za svakog pisati koji je njegov ostvaren profit. 
Takodje treba dodati da svaki agent vidi svoj ostavareni profit negde na svom ekranu (da li na početnoj strani ili uvek da se vidi negde po strani to je do vaše želje bitno je da se negde prikaže). 
Primera trenutno nema, biće dodato.

**Comment by CommandLineFox** [comment]
Pitati Mateju ili Petra ako nije jasno
