### ISSUE TITLE
Početna strana - Bagovi

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#197]
Kad se izračuna neka vrednost i obriše celo polje, i dalje ostaje izračunat broj, svaka druga promena u polju vodi do ponovnog izračunavanja treba potvrditi da li je to bag ili ne

Kad se pritisne pojedinačan račun piše "u_obradi" što bi verovatno mogli da zamenimo da bude bolje.

Moguće da će crashovati za zaposlene

StranaZaPojedinacanRacun (ili tako nesto) i UserHomePage

**Comment by CommandLineFox** [comment]
@PetarStamenic input

**Comment by stodorovic9521rn** [comment]
je l ovo sredjeno?
