### ISSUE TITLE
Odobravanje odbijanje terminskih ugovara

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#215]
Isto kao za odobravanje ordera, to za terminske

**Comment by BogBogdan** [comment]
Imam jednu stranicu odobravanje, koristicu permisiju za oba( list_orders) zove se odobravanje 2 tabelele. Gornaj tabela su porudzbine, a donja tabela termitski ugovori koje odobravam i odbijam. Ili odvojena stranica. Nece jos moci da se testira :(
