### ISSUE TITLE
Pojedinačan zaposleni: Dodatak

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#246]
Potrebno je kod editovanja i kreiranje zaposlenog dodati sledeće:
- Checkbox za supervizora
Potrebno je na stranici za pojedinačnog zaposlenog dodati sledeće
- Dugme za restartovanje limita na stranici za pojedinačnog zaposlenog, nek bude vezano za edit worker permisiju

**Comment by jovanAtRellify** [comment]
More info needed

**Comment by PetarStamenic** [comment]
¯\_(ツ)_/¯

**Comment by CommandLineFox** [comment]
Kad se zaposlenom doda bilo koja permisija koja nije `_access` staviti supervisor na true

**Comment by jovanAtRellify** [comment]
Zasto se to radi na frontu?

**Comment by CommandLineFox** [comment]
Markove bizarne avanture

Valjalo bi se čujemo sa njim danas da vidimo oko toga

**Comment by jovanAtRellify** [comment]
Checkbox
