### ISSUE TITLE
Berza: Dodatak

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#250]
~~Potrebno je doraditi naslov [Modifikacija ekrana za kupovinu hartija od vrednosti](https://docs.google.com/document/d/1dYuzetjCghWvhnTkTDrqz5Ze9q2b_Tpt/edit#heading=h.2w5ecyt)~~

~~Fali biranje računa kojim se kupuje umesto ona dva dugmeta, treba valuta da se gađa sa valutom~~

Pokazati samo dugme buy jer backend radi neki second rate shaboingery sa racunima i mi ne moramo da im saljemo racun

**Comment by CommandLineFox** [comment]
Čeka se Mateja da se odazove

**Comment by CommandLineFox** [comment]
Bek je rekao da nema biranja računa kod kupovanja akcija i tako to pa nije potrebno dodavati nikakvo biranje ni ništa nego samo da stoji opcija buy. Ako je to tako molim te proveri i yatvori issue

**Comment by jovanAtRellify** [comment]
Idalje nemam pojma o cemu se radi @CommandLineFox  @PetarStamenic
