### ISSUE TITLE
Margin call: Dodatak

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#253]
Izmirenje margin call-a nigde nema kao ni prikaz o stanju na marznom na marznom racunu [specifikacija](https://docs.google.com/document/d/1dYuzetjCghWvhnTkTDrqz5Ze9q2b_Tpt/edit#heading=h.3vac5uf)

Potrebno je prikazati informacije o marznim racunima korisnika kad se klikne na korisnika iz liste korisnika i kad se klikne na firmu da se prikaze tabela njihovih marznih racuna

Prikazati dugme za kreiranje marznih racuna kod te dve tabele (slicno tabelama koje trenutno imamo)

Takodje prikazati informacije o marznim racunima na pocetnoj strani

**Comment by CommandLineFox** [comment]
Čeka se Mateja

**Comment by BogBogdan** [comment]
Dobar dan
