### ISSUE TITLE
Profiti: Dodatak

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#254]
Potrebno je dodati [pofite na nivou banke](https://docs.google.com/document/d/1dYuzetjCghWvhnTkTDrqz5Ze9q2b_Tpt/edit#heading=h.qbm9iwg9qzx8) 

Na stranici profiti koja trenutno postoji, treba izmeniti "Profit banke" da pise profit u menjacnici jer je profit iz citave banke nesto drugo

Pored ukupnog profita menjacnice napisati Profit banke i uzeti vrednost sa rute, ruta vraca decimalni broj trebalo bi. U kontroleru za marzne racune je

**Comment by CommandLineFox** [comment]
Na stranicu Profiti dodati na vrh dropdown "Menjacnica" i "Cela banka" i u slucaju ovog drugog napraviti da pokazuje profite cele banke ima ruta za to tipa /marzniracuni/bankprofit ili tako nesto pogledaj swagger

**Comment by CommandLineFox** [comment]
Nije dropdown nego samo na stranici sacu editovati base issue

**Comment by BogBogdan** [comment]
Dobro vece
