### ISSUE TITLE
Cy 20x

### ISSUE THREAD

**Issue by jovanAtRellify** [RAF-SI-2023/Banka-4-Frontend#283]
cy 20 x rok vcrs

**Comment by CommandLineFox** [comment]
We're no strangers to love
You know the rules and so do I (do I)
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it (say it)
Inside, we both know what's been going on (going on)
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but you're too shy to say it (to say it)
Inside, we both know what's been going on (going on)
We know the game and we're gonna play it
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

**Comment by BogBogdan** [comment]
ROK ZA TASK VECERAS U PONOC

**Comment by PetarStamenic** [comment]
@CommandLineFox odobravam ovaj task produzujem rok do 1 posle ponoci

**Comment by CommandLineFox** [comment]
Bezi napravio sam issue lepo

**Comment by CommandLineFox** [comment]
Imas #290

**Comment by PetarStamenic** [comment]
sukurac radi 20 cypress recicu te majci da si ti taj koji nece da radi a ne drugi tebi je ovo zadato

**Comment by PetarStamenic** [comment]
[no](https://www.youtube.com/watch?v=vy8ewHWT9lU)

**Comment by CommandLineFox** [comment]
Odjeb
