### ISSUE TITLE
Cypress testovi

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#290]
Potrebno je kreirati cypress testove za
- Akcije
- Terminske ugovore
- Kreiranje marznih racuna (prosirenje na trenutni tab za racune)
- OTC unutar banke
- Porudzbine i prihvatanje / odbijanje porudzbina

**Comment by PetarStamenic** [comment]
nema ih 20

**Comment by CommandLineFox** [comment]
Ima pokrivenost odjebi
