### ISSUE TITLE
Zaposleni: Bagovi

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#298]
Kad dodajes zaposlenog a nisi iz banke ne smes da mu dajes permisije osim access permisija i permisije za listanje, editovanje i kreiranje zaposlenih

Lista zaposlenih, mora da pokazuje samo zaposlene iz firme kojoj pripada ulogovani zaposleni

**Comment by jovanAtRellify** [comment]
![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/119661870/c5daa4a5-6605-4e96-b6f8-7adbd781f708)
