### ISSUE TITLE
Kreiranje stranice za listu kartica

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#52]
Potrebno je kreirati stranicu liste kreditnih kartica za zaposlene i korisnike koja se nalazi u navbaru za korisnike i zaposlene

### Izgled stranice
Dugme za dodavanje kartice ukoliko je zaposleni
Lista kartica treba da sadrži sledeće informacije za svaku kreditnu karticu:
- Naziv kartice (string)
- Broj kartice (string)
- Vrsta kartice (string)
- Datum kreiranja (broj)
- Datum isteka (broj)
- Broj računa (string)
- CVV (string)
- Limit (broj)
- Status (string)

### Funkcionalnost stranice
Na osnovu broja kartice ispisati njeno ime
Ako je korisnik vidi samo svoje kartice ako je zaposleni vidi sve kartice
Dugme za dodvanje kartice vodi na stranicu za dodavanje kartica
Klikom na karticu iz liste vodi se na stranicu za pojedinačnu karticu

**Comment by Skocimis** [comment]
Uradjeno
