### ISSUE TITLE
Kreiranje stranice za dodavanje kartice

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#53]
Potrebno je kreirati stranicu za dodavanje kartice za korisnika:

### Izgled komponente
Sledeća polja
- Vrsta kartice (string) (dropdown kreditna, debitna)
- Broj računa (string)
- Limit (broj)
- Dugme kreiraj

### Funkcionalnosti komponente
Dugme kreiraj vraća nazad na listu kartica ukoliko je uspešno kreirano i pokazuje popup na vrhu za uspeh, ne može da se klikne dok nisu sva polja pravilno popunjena. Ispisati grešku ispod polja koje nike validno uneto

### Validacija komponente
Broj računa mora da ima 18 cifara

**Comment by Skocimis** [comment]
Gtv
