### ISSUE TITLE
Kreiranje stranice za pojedinačnu karticu

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#54]
Potrebno je kreirati stranicu za prikaz svih informacija za određenu karticu, u slučaju zaposlenih postoji mogućnost aktivacije odnosno deaktivacije kartice

### Izgled komponente
Izlistati sve informacije za datu karticu:
Kartica treba da ima prikazane sledeće informacije:
- Naziv kartice (string)
- Broj kartice (string)  (1111 xxxx xxxx 1111)
- Vrsta kartice (string) 
- Datum kreiranja (broj)
- Datum isteka (broj)
- Broj računa (string)
- CVV (string) (xxx)
- Limit (broj)
- Status (string)
Dugme ,,Prikaži informacije”

U slučaju stranice za zaposlene i dugmad ,,Aktiviraj”, ,,Deaktiviraj” i ,,Blokiraj”

Lista transakcija vezanih za datu karticu:
- Naziv primaoca
- Broj računa primaoca
- Iznos
- Sifra placanja
- Poziv na broj
- Svrha placanja
- Status (U obradi, uspeh, neuspeh)
- Datum i vreme transakcije
- Datum i vreme izvrsavanja

### Funkcionalnosti komponente
Na osnovu broja kartice ispisati njeno ime
Dugme prikaži informacije prikazuje pun broj kartice i pokazuje CVV
Dugme aktiviraj aktivira karticu u slučaju da je neaktivirana ili blokirana, ako je kartica već aktivna, to dugme ne može da se klikne
Dugme deaktiviraj deaktivira karticu, ne može da se klikne ako je kartica već deaktivirana
Dugme blokiraj blokira karticu, ne može da se klikne ako je već blokirana

### Validacija stranice
U slučaju greške pri promeni statusa prikazati popup na vrhu

**Comment by Skocimis** [comment]
Kraj
