### ISSUE TITLE
Kreiranje stranice za traženje kredita

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#57]
Potrebno je kreirati stranicu za traženje kredita od banke

### Izgled komponente:
Sledeća polja:
- Vrsta kredita dropdown (gotovinski, stambeni, auto, refinansirajući)
- Iznos kredita (može biti u vidu text field-a + padajući meni valuta, mora biti u odgovarajućem obliku: 296.304,55 + RSD)
- Svrha kredita
- Iznos mesečne plate (takođe može biti u obliku navedenom u polju Iznos kredita)
- Zaposlen za stalno (checkbox ili padajući meni)
- Period zaposlenja kod trenutnog poslodavca
- Ročnost
- Ekspozitura

Dugme pošalji 

Pročitati poslednji podnaslov specifikacije.

Izvući tipove iz #55

**Comment by matejavasic8321rn** [comment]
Izmena specifikacije, dogovoriti se sa backom šta će se naći na stranici za zahtevanje kredita

Polja koja forma MOŽE sadržati:

Vrsta kredita (može biti u vidu padajućeg menija koji sadrži opcije: gotovinski, stambeni, auto, refinansirajući)
Iznos kredita (može biti u vidu text field-a + padajući meni valuta, mora biti u odgovarajućem obliku: 296.304,55 + RSD)
Svrha kredita
Iznos mesečne plate (takođe može biti u obliku navedenom u polju Iznos kredita)
Zaposlen za stalno (checkbox ili padajući meni)
Period zaposlenja kod trenutnog poslodavca
Ročnost
Ekspozitura
Broj mobilnog telefona
**Broj računa (obavezno)**

**Comment by CommandLineFox** [comment]
+ userid
- mobilni
