### ISSUE TITLE
Kreiranje stranice za akcije/berzu i sve unutrašnje stranice/ekrani

### ISSUE THREAD

**Issue by matejavasic8321rn** [RAF-SI-2023/Banka-4-Frontend#60]
Potrebno je napraviti stranicu za zaposlene (biće dosupna i korisnicima ali to se trenutno razradjuje u specifikaciji, kontaktirati spec tim za pojasnjenje) preko koje će moći da pregledaju trenutne akcije na berzi i trguju njima.

### Izgled komponente
Komponenta se sastoji iz:
      - Text boxa i dugmeta za pretraživanje i dodavanje novih akcija u tabelu
      - Dugme ili tab koji otvara listu tvojih kupljenih akcija (Oznaka, Cena, Kolicina, Kolicina za prodaju, dugme kupovina)
      - Tabele sa akcijama (prikaz 5-10 akcija npr):
            - Oznaka (string velika slova 4-5 uglavnom)
            - Cena (string SA VALUTOM)
            - Volume (string)
            - Promena (decimalni broj sa strelicom gore ili dole, obojeno u zeleno ili crveno zavisnosti od rasta ili pada)
            - Promena u procentima(bojenje kao i gore)
            - Poslednje ažuriranje (17.03.2024. 13:20)
            - Dugme kupi
            - Dugme prodaj 
            - Dugme ili šta mislite da treba da se ukloni iz tabele odabrana akcija

Ekran za detalje akcije: 
        - Logo 
        - Oznaka
        - Pun naziv akcije/kompanije
        - Prikaz da li je berza aktivna ili ne (radno vreme berze)
        - Cena tretnurna
        - High cena 
        - Low cena
        - Grafik sa podešavajućim time frameom (1d 5d 1m 6m 1y ytd)
        - Detalji ispod grafika gde imamo:
        - Change (u izabranom time frame-u)
        - Day range
        - Open 
        - Volume 
        - Outstanding shares
        - Previous Close 
        - Dugme za opcije

Ekran kupovina hartije:
        - Imamo labele i text boxove za njih. Količina, Limit, Stop
        - CheckBox AllOrNone
        - CheckBox Marign
        - Dugme kupi 
        - Napomene koje treba i  napisati:
        - * Ako su oba 0 onda se radi Market Order
        - * Ako je jedan stavljen, a drugi 0, radi se šta ste odabrali (Limit ili Stop Order)
        - * Ako su oba stavljena, radi se Stop-Limit order

Ekran za OTC prodaju hartije:
      - Labela cena po komadu i cena (fixirana u tom trenutku koja je)
      - Amount labela i text box gde korisnik upisuje željenu količinu 
      - Valuta u kojo kupuje (najčešće USD ili EUR)
      - Ugovor (dropdown manu ugovora koje korisnik ima)
      - Dugme prodaj tj dodavanje OTC listinga

### Funkcionalnsti komponente
Klikom na bilo koju akciju u tabeli otvara se ekran za detalje te akcije
Klikom na kupi akciju otvara se ekran kupovina hartije
Klikom na kupi na ekranu kupovina hartije treba izbaciti ekran za potvrdu ili odbijanje kupovine gde korisnik može videti sve detalje kupovine i da prihvati ili odbije kupovinu. Ukoliko kupi izbaciti popup uspešna ili neuspešna kupovina (npr nema dovoljno para na računu).
Klikom na dugme prodaj otvara se ekran OTC prodaja hartije
Klikom na dugme prodaj/dodaj listing za OTC prodaju otvara se popup/ekran na kome se vide svi detalji prodaje i dugme prihvati i odustani i odgovarajuci popup za uspesnost akcije.
Klikom na akcije koje poseduje korisnik, otvara se ekran sa svim starim orderima (Tip Ordera, Tip Transakcije (buy sell), kolicina, ukupna cena, datum)
U svim tabelama sortiranje može po svim kolonama

### Napomene:
   Za inspiraciju iskoristiti https://banka-2.k8s.elab.rs/stocks 
   Za sva pitanja ili nedefinisane stvari cimajte spec

**Comment by jovanAtRellify** [comment]
Zasto je ovo jedan task umesto cetiri? @CommandLineFox
