### ISSUE TITLE
Potrebno je kreirati sve potrebne stranice za rad sa terminskim ugovorima I funkcionalnostima unutar njih

### ISSUE THREAD

**Issue by CommandLineFox** [RAF-SI-2023/Banka-4-Frontend#88]
Stranica1:
Potrebno je prikazati 5 različitih kategorija terminskih ugovora (Agriculture, Energy, Meats, Metals, Softs). Klikom na neku od tih kategorija otvara se nova stranica (ili dropdown kao u prošlogodišnjem gde se prikazuju pojedinačni derivati koji su u toj kategoriji).

Stranica2: Prikaz derivata(sirovina) kojima se trguje, npr za Agriculture: Corn, Soybean, Soybean Oil...). 
Svaki derivat ima ime i Contract unit, Contract Size i Maintenance Margin naslove i prikaz. Klikom na neku od tih stvari otvara se Stranica3.

Stranica3:
Na vrhu stoji naslov koji je ime derivata. Postoje dve kartice:
Jedna je Terminski ugovori i kada je ona selektovana ispod se prikazuje tabela koja prikazuje detalje konkretnog ugovora: Naziv, Vlasnik, Cena, Datum, dugme za kupovinu i dugme za prodaju. Druga kartica je Moji terminski ugovori koji klikom otvara Stranicu4. Klikom na dugme kupi otvara se popup koji na sebi ima 2 Labele, Limit i Stop i 2 polja gde mogu da se unesu vrednosti za te labele i dugme kupi koje izvršava kupovinu (prebacuje terminski ugovor u karticu2).

Stranica4: 
Ista kao Stranica 3 samo prikazuje korisnikove terminske ugovore koji u tabeli imaju sledeće podatke.
Naziv,Na prodaju (na prodaju ili nije na prodaju), Cena, Datum, dugme Prodaj (ili skloni sa prodaje ako je na prodaju). 

Napomena za stranicu 2 i 3: Ako se ima previše entiteta potrebno je napraviti sistem da se lista više (ili da se samo redja “beskonacno” mnogo ugovora ili da se prikazuje fiksan broj ugovora pa da se lista levo desno po “stranicama”). Kontaktirati specifikaciju za primere od prošle godine ukoliko se prekine pristup.

![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/33495263/212644b2-209c-4521-9e4a-10c6d3f6906d)
![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/33495263/a8a00b62-7c3c-4132-a6d8-f1621c2fd705)
![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/33495263/04442cb3-bfdc-4429-805c-cd0746551bc2)
![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/33495263/3d40af88-7710-4120-866e-118aa44cf10f)
![image](https://github.com/RAF-SI-2023/Banka-4-Frontend/assets/33495263/834d7d2f-2e84-4302-8950-6ee6a00d02d3)

Ukoliko imate neka pitanja obratite se sekretarici

**Comment by matejavasic8321rn** [comment]
Društvo moram da vas iscimam za jednu stvar koju nisam na vreme video. Kada se kupi terminski ugovor da bi on postao "naš" tj da bi ka prebacili u deo moji terminski ugovori potrebno je da se sačeka settlementdate, ali da ne bi tada on bio u voidu nekom prebacićemo ga odmah ali ćemo onda imati dodatni jedno polje, recimo status ili nešto gde će pisati "čeka se settlement date" ili sam ikonica satića ili nešto tako. Na backu ce to biti samo jedan boolean

Ukratko: Treba dodati kolonu za status za future na stranici Moji Terminski Ugovori. Taj status će prikazivati da li je on kupljen ili ne. Tj da li je prošla transakcija ili je samo "rezervisan".

**Comment by CommandLineFox** [comment]
Garbeđ kolektor
